### ISSUE TITLE
Oqtane Docs 404 Errors

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.docs#103]
I am not sure what changed, but when I search for information about Oqtane and get results pointing to the Oqtane Docs:

![image](https://github.com/user-attachments/assets/c7fe0ece-7047-4657-8015-18ab343b1c1d)

When I navigate to them, they result in 404 errors:

![image](https://github.com/user-attachments/assets/33ab716b-de96-4f2b-94f8-aa88484315c5)

**Comment by iJungleboy** [comment]
We just moved some things around last week, so I guess we'll have to wait for a google reindex.

should fix itself within a few days.

**Comment by iJungleboy** [comment]
We can do this, but it's quite a bit of work as we need to do this for every moved page.

ATM it's a bit much, but as the docs mature, I'll add that as well.
