### ISSUE TITLE
Create Discussion Board

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.docs#18]
Should we create a discussion board to make more friendly discussions take place instead of feeling like you can only talk issues like a spelling error or adding new things?  We can link and discuss more information in a more casual way enhancing productivity towards documentation.

**Comment by iJungleboy** [comment]
@thabaum I'm just getting started from vacation, so still a bit slow here. 

I will also check your pull requests within the next 2-3 days, thank you sooo much!

Discussions sounds great, I'll enable them.

**Comment by thabaum** [comment]
@iJungleboy you rock man!
