### ISSUE TITLE
Document the Schema

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.docs#3]
I'd like to document the schema to help myself and other better understand the roles of the tables and various fields.

**Comment by iJungleboy** [comment]
Sure, go ahead. Such documentation uses the normal Markdown syntax. 

Just do as much as you need, and I'll review it or move it to a better place once it's ready.

**Comment by markdav-is** [comment]
cool.  I've been doing docfx documents at work and I can contribute them over here as well.

**Comment by iJungleboy** [comment]
awesome. Then try to get started and ping me if you have it working. 

BTW: As of now the docs were still built using Oqtane 1, I haven't been able to build w/v2 because of .net 5 and I'm not sure if this is a general problem, or just something with my PC where I may have misconfigured MSBuild.

**Comment by GregStevenson** [comment]
Was any progress ever made on this issue? @markdav-is mentioned some documents he had. Were they actually integrated. If there is no objection, I'm willing to work on this issue so that we have the v5 schema documented.

**Comment by thabaum** [comment]
@iJungleboy I believe I resolved the build issue #12 with pull request #15 as I was able to build this project after fixing an issue I had.  However not sure it is the same build issue.  I had 2 successful builds and left it at that after using `dotnet tool restore` command using terminal in Visual Studio.

I also went ahead and updated the Oqtane 5 information, updated the project to .NET 8 and changed .config json file to latest version of docFX and put out a few other PRs and ideas along the way.

@GregStevenson and @markdav-is it would be nice to see some coordination reviewing and improving docs by submitting pull requests.  Contributing to discussions and issues here would be nice as well by everyone.  The blog has a lot of great helpful information as with all the open and closed Oqtane.Framework discussions, issues and pull requests if browsing around and find some things worthy of including.

I would like to see the structure more presented as shown in issue #16 I created to discuss how I feel we could make a clear path for anyone looking to get somewhere fast with well thought out documentation.  It is just an idea for where to put even more pages as needed to help showcase and explain all parts of the Oqtane Framework worth noting.

I will do my best to contribute a fair share to start with and improve upon down the road for most all these pages/sections.  Combined with what has already been done to get us here and what is being offered by the others in the community we should get a fairly decent documentation solution for Oqtane v5 by next major release.

I am hoping the build issue is resolved with PR #15.  I can submit a PR for what I feel could be an acceptable solution as described in issue #16.  I maybe off in left field here not sure until I get my feet a little more wet helping with this.  Some things I want documented for my own reference later which is my main interest along with helping this community when I can.

Cheers!

**Comment by thabaum** [comment]
Anyone moving forward here?

**Comment by thabaum** [comment]
@markdav-is are you still interested in performing this task?  Or @GregStevenson?  Discord could be used to collaborate potentially if you two can connect on this topic.  I can probably do it eventually if no one gets around to it after I knock out the other issues I created.  It is kind of lonely here ;)

**Comment by thabaum** [comment]
@iJungleboy can close with #91 ?!
