### ISSUE TITLE
Enhance contributor documentation with media guidelines.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.docs#49]
Should we add some general guidelines and resources for creating and including media files such as videos and images?  I would like to remove a few that link off-site videos for example and create a walk-through of images instead if I can recall as as example.

Understanding our goals for how the docs will keep and store information relating to the Oqtane Framework in-house so to speak especially with videos and images.

General guidelines such as size, format, easy and free to use photo editing tools such as Gimp or just using screenshots from windows and so on so a consistent feel can be kept between resources.

https://docs.oqtane.org/guides/docs/conventions.html I believe is where this can be included, maybe a page on media alone.  We should have a how-to section for helping us (me) do this confidently if we can provide one.

Images and videos are big part of documentation and I just want a little guidance here I am not locating currently.

**Comment by iJungleboy** [comment]
Feel free to add something if you wish, but don't overdo it. 

The risk is that we try to make things too perfect - making it harder to contribute. 
I would rather have images which are not perfect, than no contributions ;)

+ most developers should know how to edit images and be capable of print-screens. 
I don't think we should cater to people who struggle with this.

**Comment by thabaum** [comment]
I was just trying to clear up any concerns, if it is the wild west, let us know this in contribution section.  This would clear up the fog of anyone that wants to contribute with this concern and let them know and understand the lax guidelines.  For a first timer doing docs, I don't know if there is a proper way to handle things in docs.  If you can think of something that can be added to this area to explain this about media files I think it would help a potential contributor.

Like you said something simple and not overthought, I had the question, didn't know the answer and was backing off from doing anything until I read this ;)
