### ISSUE TITLE
[DOC] ReadMe.md: Add Link To Discord Community Server

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.docs#77]
# Documentation Request
ReadMe.md: Add Link to Discord Community Server

## Description 
Request to include a link to the Discord community server in the README.md file. This addition will facilitate better engagement and support for users by directing them to the community for collaboration and discussion.

Action Items:

- Add a prominent link to the Discord community server in the README.md.
- Include a brief description of the server's purpose and how users can benefit from joining.

This update will enhance community connectivity and support.

**Comment by iJungleboy** [comment]
thx.
I also added it to the home page in the docs
